[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "click==8.1.7",
    "matplotlib>=3.10.3",
    "pandas>=2.3.1",
    "yfinance>=0.2.65",
]
